(definstances period-instances
	(Mannerism of Period
		(year_beginning 1520)
		(year_end 1600)
	)
	(Proto-Renaissance of Period
		(year_beginning 1300)
		(year_end 1400)
	)
	(Expressionism of Period
		(year_beginning 1905)
		(year_end 1933)
	)
	(Early_Renaissance of Period
		(year_beginning 1400)
		(year_end 1500)
	)
	(Islamic_Golden_Age of Period
		(year_beginning 1250)
		(year_end 1380)
	)
	(Cubism of Period
		(year_beginning 1907)
		(year_end 1930)
	)
	(Romanticism of Period
		(year_beginning 1790)
		(year_end 1850)
	)
	(Post-Impressionism of Period
		(year_beginning 1880)
		(year_end 1910)
	)
	(Gothic of Period
		(year_beginning 1140)
		(year_end 1400)
	)
	(Realism of Period
		(year_beginning 1848)
		(year_end 1900)
	)
	(High_Renaissance of Period
		(year_beginning 1500)
		(year_end 1520)
	)
	(Abstract_Expressionism of Period
		(year_beginning 1940)
		(year_end 1960)
	)
	(Neoclassicism of Period
		(year_beginning 1760)
		(year_end 1790)
	)
	(Romanesque of Period
		(year_beginning 1000)
		(year_end 1150)
	)
	(Rococo of Period
		(year_beginning 1720)
		(year_end 1760)
	)
	(Contemporary_Art of Period
		(year_beginning 1980)
		(year_end 2000)
	)
	(Impressionism of Period
		(year_beginning 1860)
		(year_end 1880)
	)
	(Surrealism of Period
		(year_beginning 1920)
		(year_end 1950)
	)
	(Pop_Art of Period
		(year_beginning 1960)
		(year_end 1980)
	)
	(Early_Baroque of Period
		(year_beginning 1600)
		(year_end 1650)
	)
	(High_Baroque of Period
		(year_beginning 1650)
		(year_end 1720)
	)
)

(definstances author-instances
	(author357 of Author
		(author_id 357)
		(author_name "Fra Bartolommeo")
	)
	(author170 of Author
		(author_id 170)
		(author_name "Francesco Mochi")
	)
	(author126 of Author
		(author_id 126)
		(author_name "Case attributed")
	)
	(author122 of Author
		(author_id 122)
		(author_name "Peter Blume")
	)
	(author187 of Author
		(author_id 187)
		(author_name "Francis Picabia")
	)
	(author319 of Author
		(author_id 319)
		(author_name "John Quincy")
	)
	(author115 of Author
		(author_id 115)
		(author_name "Jacques de")
	)
	(author2 of Author
		(author_id 2)
		(author_name "Henri Matisse")
	)
	(author8 of Author
		(author_id 8)
		(author_name "Sir Joshua")
	)
	(author161 of Author
		(author_id 161)
		(author_name "China, probably")
	)
	(author326 of Author
		(author_id 326)
		(author_name "India Madhya")
	)
	(author150 of Author
		(author_id 150)
		(author_name "Arthur Dove")
	)
	(author385 of Author
		(author_id 385)
		(author_name "Julia Fish")
	)
	(author71 of Author
		(author_id 71)
		(author_name "Jacques-Louis David")
	)
	(author250 of Author
		(author_id 250)
		(author_name "Frank Lloyd")
	)
	(author32 of Author
		(author_id 32)
		(author_name "Édouard Manet")
	)
	(author195 of Author
		(author_id 195)
		(author_name "Willem de")
	)
	(author139 of Author
		(author_id 139)
		(author_name "Paul Cezanne")
	)
	(author110 of Author
		(author_id 110)
		(author_name "André Kertész")
	)
	(author374 of Author
		(author_id 374)
		(author_name "Hernán Díaz")
	)
	(author381 of Author
		(author_id 381)
		(author_name "Spain; probably")
	)
	(author280 of Author
		(author_id 280)
		(author_name "Paul Delvaux")
	)
	(author194 of Author
		(author_id 194)
		(author_name "Jackson Pollock")
	)
	(author281 of Author
		(author_id 281)
		(author_name "Joan Miró")
	)
	(author116 of Author
		(author_id 116)
		(author_name "Designed by")
	)
	(author367 of Author
		(author_id 367)
		(author_name "China")
	)
	(author103 of Author
		(author_id 103)
		(author_name "Andy Warhol")
	)
	(author33 of Author
		(author_id 33)
		(author_name "Claude Monet")
	)
	(author29 of Author
		(author_id 29)
		(author_name "India Andhra")
	)
	(author0 of Author
		(author_id 0)
		(author_name "Meindert Hobbema")
	)
	(author109 of Author
		(author_id 109)
		(author_name "Henri Cartier-Bresson")
	)
	(author196 of Author
		(author_id 196)
		(author_name "Ivan Albright")
	)
	(author37 of Author
		(author_id 37)
		(author_name "Bernat Martorell")
	)
	(author42 of Author
		(author_id 42)
		(author_name "Rogier van")
	)
	(author82 of Author
		(author_id 82)
		(author_name "Augsburg, Germany")
	)
	(author336 of Author
		(author_id 336)
		(author_name "Julia Margaret")
	)
	(author36 of Author
		(author_id 36)
		(author_name "William Glackens")
	)
	(author87 of Author
		(author_id 87)
		(author_name "China")
	)
	(author118 of Author
		(author_id 118)
		(author_name "Maria Helena")
	)
	(author421 of Author
		(author_id 421)
		(author_name "Marcel Duchamp")
	)
	(author78 of Author
		(author_id 78)
		(author_name "William Merritt")
	)
	(author134 of Author
		(author_id 134)
		(author_name "Henri de")
	)
	(author18 of Author
		(author_id 18)
		(author_name "James McNeill")
	)
	(author255 of Author
		(author_id 255)
		(author_name "Case designed")
	)
	(author136 of Author
		(author_id 136)
		(author_name "Edgar Degas")
	)
	(author243 of Author
		(author_id 243)
		(author_name "Rosalba Carriera")
	)
	(author83 of Author
		(author_id 83)
		(author_name "René Magritte")
	)
	(author165 of Author
		(author_id 165)
		(author_name "Marion Mahony")
	)
	(author59 of Author
		(author_id 59)
		(author_name "India Tamil")
	)
	(author288 of Author
		(author_id 288)
		(author_name "Georges Vantongerloo")
	)
	(author334 of Author
		(author_id 334)
		(author_name "Yamakawa Shuho")
	)
	(author258 of Author
		(author_id 258)
		(author_name "Marc Chagall")
	)
	(author38 of Author
		(author_id 38)
		(author_name "Zao Wou-Ki")
	)
	(author290 of Author
		(author_id 290)
		(author_name "Georges Braque")
	)
	(author128 of Author
		(author_id 128)
		(author_name "Marc Chagall")
	)
	(author10 of Author
		(author_id 10)
		(author_name "Francis Bacon")
	)
	(author203 of Author
		(author_id 203)
		(author_name "Henri Matisse")
	)
	(author315 of Author
		(author_id 315)
		(author_name "Meissen Porcelain")
	)
	(author272 of Author
		(author_id 272)
		(author_name "Designed by")
	)
	(author158 of Author
		(author_id 158)
		(author_name "John Singer")
	)
	(author3 of Author
		(author_id 3)
		(author_name "Giovanni Battista")
	)
	(author50 of Author
		(author_id 50)
		(author_name "Claude Monet")
	)
	(author45 of Author
		(author_id 45)
		(author_name "Paul Cezanne")
	)
	(author181 of Author
		(author_id 181)
		(author_name "India Designed")
	)
	(author60 of Author
		(author_id 60)
		(author_name "Giovanni Battista")
	)
	(author419 of Author
		(author_id 419)
		(author_name "Sebastiano del")
	)
	(author49 of Author
		(author_id 49)
		(author_name "Claude Monet")
	)
	(author138 of Author
		(author_id 138)
		(author_name "Frans Snyders")
	)
	(author189 of Author
		(author_id 189)
		(author_name "After a")
	)
	(author379 of Author
		(author_id 379)
		(author_name "Rudolph Schindler")
	)
	(author200 of Author
		(author_id 200)
		(author_name "Cambodia Angkor")
	)
	(author251 of Author
		(author_id 251)
		(author_name "Joachim Antonisz.")
	)
	(author219 of Author
		(author_id 219)
		(author_name "Moche North")
	)
	(author97 of Author
		(author_id 97)
		(author_name "Designed by")
	)
	(author154 of Author
		(author_id 154)
		(author_name "Edward Steichen")
	)
	(author58 of Author
		(author_id 58)
		(author_name "Gustave Caillebotte")
	)
	(author282 of Author
		(author_id 282)
		(author_name "Charles White")
	)
	(author88 of Author
		(author_id 88)
		(author_name "England")
	)
	(author156 of Author
		(author_id 156)
		(author_name "Georg Baselitz")
	)
	(author352 of Author
		(author_id 352)
		(author_name "Jasper Johns")
	)
	(author44 of Author
		(author_id 44)
		(author_name "Francisco José")
	)
	(author25 of Author
		(author_id 25)
		(author_name "Hermann Dudley")
	)
	(author53 of Author
		(author_id 53)
		(author_name "Pablo Picasso")
	)
	(author46 of Author
		(author_id 46)
		(author_name "Giovanni Battista")
	)
	(author142 of Author
		(author_id 142)
		(author_name "Carleton E.")
	)
	(author119 of Author
		(author_id 119)
		(author_name "Salado branch")
	)
	(author397 of Author
		(author_id 397)
		(author_name "Sylvia Plimack")
	)
	(author248 of Author
		(author_id 248)
		(author_name "Giovanni Benedetto")
	)
	(author403 of Author
		(author_id 403)
		(author_name "Jack Whitten")
	)
	(author9 of Author
		(author_id 9)
		(author_name "Joseph Mallord")
	)
	(author245 of Author
		(author_id 245)
		(author_name "Georgia O'Keeffe")
	)
	(author404 of Author
		(author_id 404)
		(author_name "Joaquín Torres-García")
	)
	(author209 of Author
		(author_id 209)
		(author_name "Suzuki Harunobu")
	)
	(author185 of Author
		(author_id 185)
		(author_name "Yao Shou")
	)
	(author213 of Author
		(author_id 213)
		(author_name "Thomas Cole")
	)
	(author101 of Author
		(author_id 101)
		(author_name "Spanish, León")
	)
	(author408 of Author
		(author_id 408)
		(author_name "Mark Bradford")
	)
	(author111 of Author
		(author_id 111)
		(author_name "Caspar David")
	)
	(author310 of Author
		(author_id 310)
		(author_name "Paulus Potter")
	)
	(author144 of Author
		(author_id 144)
		(author_name "Egyptian; Thebes")
	)
)

(definstances theme-instances
	(emotional of Theme
		(labels (create$ "Sadness" "Joy" "Nostalgia" "Hope" "Love" "Despair"))
	)
	(historical of Theme
		(labels (create$ "Battles and Wars" "Conquests" "Revolutions" "Antiquity" "Monarchies" "Colonizations"))
	)
	(religious of Theme
		(labels (create$ "Christianity" "Islam" "Greek Mythology" "Roman Mythology" "Egyptian Religion" "Buddhism"))
	)
	(natural of Theme
		(labels (create$ "Landscapes" "Fauna" "Flora" "Maritime Scenes" "Meteorological Phenomena" "Mountains and Valleys"))
	)
	(mystical of Theme
		(labels (create$ "Magic" "Occult" "Astrology" "Alchemy" "Mysticism" "Ancient Rituals"))
	)
)

(definstances museum-instances
	(main-museum of Museum
		(museum_id 1)
		(museum_name "MyMuseum")
	)
)

(definstances room-instances
	(room101 of Room
		(room_id 101)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room102 of Room
		(room_id 102)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room103 of Room
		(room_id 103)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room201 of Room
		(room_id 201)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room202 of Room
		(room_id 202)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room203 of Room
		(room_id 203)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(room100 of Room
		(room_id 100)
		(room_in_museum [main-museum])
		(is_entry TRUE)
		(is_exit TRUE)
		(is_stairs FALSE)
		(is_elevator FALSE)
	)
	(elevator_2_to_1 of Room
		(room_id None)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs FALSE)
		(is_elevator TRUE)
	)
	(stair_2_to_1_0 of Room
		(room_id None)
		(room_in_museum [main-museum])
		(is_entry FALSE)
		(is_exit FALSE)
		(is_stairs TRUE)
		(is_elevator FALSE)
	)
)

(definstances artwork-instances
	(artwork_4796 of Artwork
		(artwork_id 4796)
		(artwork_name "Fishing Boats with Hucksters Bargaining for Fish")
		(artwork_in_room [room202])
		(created_by [author9])
		(artwork_in_period [Romanticism])
		(artwork_theme "Love")
		(default_time 8)
	)
	(artwork_188540 of Artwork
		(artwork_id 188540)
		(artwork_name "Sur, Long Island City, New York")
		(artwork_in_room [room203])
		(created_by [author374])
		(artwork_in_period [Gothic])
		(artwork_theme "Christianity")
		(default_time 7)
	)
	(artwork_111642 of Artwork
		(artwork_id 111642)
		(artwork_name "The Awakening of the Forest")
		(artwork_in_room [room102])
		(created_by [author280])
		(artwork_in_period [Surrealism])
		(artwork_theme "Occult")
		(default_time 8)
	)
	(artwork_111654 of Artwork
		(artwork_id 111654)
		(artwork_name "The Policeman")
		(artwork_in_room [room101])
		(created_by [author281])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 8)
	)
	(artwork_47149 of Artwork
		(artwork_id 47149)
		(artwork_name "Mao")
		(artwork_in_room [room201])
		(created_by [author103])
		(artwork_in_period [Pop_Art])
		(artwork_theme "Sadness")
		(default_time 11)
	)
	(artwork_13853 of Artwork
		(artwork_id 13853)
		(artwork_name "Karttikeya, Commander of the Divine Army, Seated on a Peacock")
		(artwork_in_room [room202])
		(created_by [author29])
		(artwork_in_period [Early_Renaissance])
		(artwork_theme "Hope")
		(default_time 7)
	)
	(artwork_50148 of Artwork
		(artwork_id 50148)
		(artwork_name "Hyères, France")
		(artwork_in_room [room102])
		(created_by [author109])
		(artwork_in_period [Surrealism])
		(artwork_theme "Occult")
		(default_time 3)
	)
	(artwork_15468 of Artwork
		(artwork_id 15468)
		(artwork_name "Saint George and the Dragon")
		(artwork_in_room [room103])
		(created_by [author37])
		(artwork_in_period [Early_Renaissance])
		(artwork_theme "Christianity")
		(default_time 6)
	)
	(artwork_157056 of Artwork
		(artwork_id 157056)
		(artwork_name "Mrs. Herbert Duckworth")
		(artwork_in_room [room101])
		(created_by [author336])
		(artwork_in_period [Impressionism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_53001 of Artwork
		(artwork_id 53001)
		(artwork_name "Composition")
		(artwork_in_room [room101])
		(created_by [author118])
		(artwork_in_period [Surrealism])
		(artwork_theme "Mysticism")
		(default_time 5)
	)
	(artwork_238749 of Artwork
		(artwork_id 238749)
		(artwork_name "Bottle Rack (Porte-Bouteilles)")
		(artwork_in_room [room102])
		(created_by [author421])
		(artwork_in_period [Expressionism])
		(artwork_theme "Astrology")
		(default_time 4)
	)
	(artwork_8958 of Artwork
		(artwork_id 8958)
		(artwork_name "Arrangement in Flesh Color and Brown: Portrait of Arthur Jerome Eddy")
		(artwork_in_room [room201])
		(created_by [author18])
		(artwork_in_period [Realism])
		(artwork_theme "Sadness")
		(default_time 7)
	)
	(artwork_61603 of Artwork
		(artwork_id 61603)
		(artwork_name "Ballet at the Paris Opéra")
		(artwork_in_room [room201])
		(created_by [author136])
		(artwork_in_period [Impressionism])
		(artwork_theme "Joy")
		(default_time 7)
	)
	(artwork_71829 of Artwork
		(artwork_id 71829)
		(artwork_name "Rock Crest/Rock Glen, Mason City, Iowa, Perspective")
		(artwork_in_room [room201])
		(created_by [author165])
		(artwork_in_period [Expressionism])
		(artwork_theme "Joy")
		(default_time 6)
	)
	(artwork_118746 of Artwork
		(artwork_id 118746)
		(artwork_name "Interrelation of Volumes from the Ellipsoid")
		(artwork_in_room [room102])
		(created_by [author288])
		(artwork_in_period [Surrealism])
		(artwork_theme "Occult")
		(default_time 4)
	)
	(artwork_109439 of Artwork
		(artwork_id 109439)
		(artwork_name "America Windows")
		(artwork_in_room [room203])
		(created_by [author258])
		(artwork_in_period [Pop_Art])
		(artwork_theme "Sadness")
		(default_time 5)
	)
	(artwork_119521 of Artwork
		(artwork_id 119521)
		(artwork_name "Landscape at L'Estaque")
		(artwork_in_room [room101])
		(created_by [author290])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 5)
	)
	(artwork_59426 of Artwork
		(artwork_id 59426)
		(artwork_name "White Crucifixion")
		(artwork_in_room [room102])
		(created_by [author128])
		(artwork_in_period [Surrealism])
		(artwork_theme "Alchemy")
		(default_time 7)
	)
	(artwork_147508 of Artwork
		(artwork_id 147508)
		(artwork_name "Oil or Vinegar Cruet")
		(artwork_in_room [room203])
		(created_by [author315])
		(artwork_in_period [Rococo])
		(artwork_theme "Greek Mythology")
		(default_time 3)
	)
	(artwork_111400 of Artwork
		(artwork_id 111400)
		(artwork_name "Samovar")
		(artwork_in_room [room101])
		(created_by [author272])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_16571 of Artwork
		(artwork_id 16571)
		(artwork_name "Arrival of the Normandy Train, Gare Saint-Lazare")
		(artwork_in_room [room102])
		(created_by [author50])
		(artwork_in_period [Impressionism])
		(artwork_theme "Landscapes")
		(default_time 5)
	)
	(artwork_23333 of Artwork
		(artwork_id 23333)
		(artwork_name "Pastoral Scene")
		(artwork_in_room [room103])
		(created_by [author60])
		(artwork_in_period [Rococo])
		(artwork_theme "Greek Mythology")
		(default_time 7)
	)
	(artwork_62042 of Artwork
		(artwork_id 62042)
		(artwork_name "Still Life with Dead Game, Fruits, and Vegetables in a Market")
		(artwork_in_room [room103])
		(created_by [author138])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Occult")
		(default_time 9)
	)
	(artwork_86340 of Artwork
		(artwork_id 86340)
		(artwork_name "Head of a Male Deity (Deva)")
		(artwork_in_room [room103])
		(created_by [author200])
		(artwork_in_period [High_Baroque])
		(artwork_theme "Christianity")
		(default_time 5)
	)
	(artwork_43714 of Artwork
		(artwork_id 43714)
		(artwork_name "E-10: English Dining Room of the Georgian Period, 1770-90")
		(artwork_in_room [room102])
		(created_by [author97])
		(artwork_in_period [Surrealism])
		(artwork_theme "Magic")
		(default_time 5)
	)
	(artwork_20684 of Artwork
		(artwork_id 20684)
		(artwork_name "Paris Street; Rainy Day")
		(artwork_in_room [room201])
		(created_by [author58])
		(artwork_in_period [Realism])
		(artwork_theme "Sadness")
		(default_time 9)
	)
	(artwork_68823 of Artwork
		(artwork_id 68823)
		(artwork_name "Woodman (Waldarbeiter)")
		(artwork_in_room [room201])
		(created_by [author156])
		(artwork_in_period [Pop_Art])
		(artwork_theme "Sadness")
		(default_time 8)
	)
	(artwork_16362 of Artwork
		(artwork_id 16362)
		(artwork_name "Friar Pedro Shoots El Maragato as His Horse Runs Off")
		(artwork_in_room [room101])
		(created_by [author44])
		(artwork_in_period [Romanticism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_16488 of Artwork
		(artwork_id 16488)
		(artwork_name "Armida Encounters the Sleeping Rinaldo")
		(artwork_in_room [room201])
		(created_by [author46])
		(artwork_in_period [Rococo])
		(artwork_theme "Joy")
		(default_time 8)
	)
	(artwork_55249 of Artwork
		(artwork_id 55249)
		(artwork_name "Ritual Cache")
		(artwork_in_room [room103])
		(created_by [author119])
		(artwork_in_period [Gothic])
		(artwork_theme "Battles and Wars")
		(default_time 6)
	)
	(artwork_104031 of Artwork
		(artwork_id 104031)
		(artwork_name "The Shelton with Sunspots, N.Y.")
		(artwork_in_room [room101])
		(created_by [author245])
		(artwork_in_period [Cubism])
		(artwork_theme "Mysticism")
		(default_time 6)
	)
	(artwork_88977 of Artwork
		(artwork_id 88977)
		(artwork_name "Evening Snow on a Floss Shaper (Nurioke no bosetsu), from the series Eight Views of the Parlor (Zashiki hakkei)")
		(artwork_in_room [room103])
		(created_by [author209])
		(artwork_in_period [Neoclassicism])
		(artwork_theme "Revolutions")
		(default_time 3)
	)
	(artwork_90048 of Artwork
		(artwork_id 90048)
		(artwork_name "Distant View of Niagara Falls")
		(artwork_in_room [room202])
		(created_by [author213])
		(artwork_in_period [Romanticism])
		(artwork_theme "Love")
		(default_time 4)
	)
	(artwork_225016 of Artwork
		(artwork_id 225016)
		(artwork_name "A Siren Beside a Ship")
		(artwork_in_room [room101])
		(created_by [author408])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Mysticism")
		(default_time 10)
	)
	(artwork_146953 of Artwork
		(artwork_id 146953)
		(artwork_name "Two Cows and a Young Bull beside a Fence in a Meadow")
		(artwork_in_room [room103])
		(created_by [author310])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Occult")
		(default_time 4)
	)
	(artwork_184371 of Artwork
		(artwork_id 184371)
		(artwork_name "The Nativity")
		(artwork_in_room [room203])
		(created_by [author357])
		(artwork_in_period [High_Renaissance])
		(artwork_theme "Christianity")
		(default_time 4)
	)
	(artwork_57819 of Artwork
		(artwork_id 57819)
		(artwork_name "Wall Clock")
		(artwork_in_room [room203])
		(created_by [author126])
		(artwork_in_period [Rococo])
		(artwork_theme "Greek Mythology")
		(default_time 6)
	)
	(artwork_56682 of Artwork
		(artwork_id 56682)
		(artwork_name "The Rock")
		(artwork_in_room [room102])
		(created_by [author122])
		(artwork_in_period [Surrealism])
		(artwork_theme "Occult")
		(default_time 7)
	)
	(artwork_52560 of Artwork
		(artwork_id 52560)
		(artwork_name "Corpus of Christ, from the Altarpiece of the Crucifixion")
		(artwork_in_room [room202])
		(created_by [author115])
		(artwork_in_period [Gothic])
		(artwork_theme "Monarchies")
		(default_time 3)
	)
	(artwork_4788 of Artwork
		(artwork_id 4788)
		(artwork_name "Lady Sarah Bunbury Sacrificing to the Graces")
		(artwork_in_room [room202])
		(created_by [author8])
		(artwork_in_period [Neoclassicism])
		(artwork_theme "Antiquity")
		(default_time 8)
	)
	(artwork_153244 of Artwork
		(artwork_id 153244)
		(artwork_name "Cow Suckling a Calf")
		(artwork_in_room [room203])
		(created_by [author326])
		(artwork_in_period [Early_Renaissance])
		(artwork_theme "Christianity")
		(default_time 5)
	)
	(artwork_189932 of Artwork
		(artwork_id 189932)
		(artwork_name "Bloom")
		(artwork_in_room [room203])
		(created_by [author385])
		(artwork_in_period [Contemporary_Art])
		(artwork_theme "Christianity")
		(default_time 5)
	)
	(artwork_105203 of Artwork
		(artwork_id 105203)
		(artwork_name "Triptych Window from the Coonley Playhouse, Riverside, Illinois")
		(artwork_in_room [room203])
		(created_by [author250])
		(artwork_in_period [Expressionism])
		(artwork_theme "Sadness")
		(default_time 6)
	)
	(artwork_83889 of Artwork
		(artwork_id 83889)
		(artwork_name "Two Women's Torsos")
		(artwork_in_room [room101])
		(created_by [author195])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Mysticism")
		(default_time 5)
	)
	(artwork_62371 of Artwork
		(artwork_id 62371)
		(artwork_name "Madame Cezanne in a Yellow Chair")
		(artwork_in_room [room201])
		(created_by [author139])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Nostalgia")
		(default_time 5)
	)
	(artwork_83642 of Artwork
		(artwork_id 83642)
		(artwork_name "Greyed Rainbow")
		(artwork_in_room [room102])
		(created_by [author194])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Astrology")
		(default_time 8)
	)
	(artwork_185963 of Artwork
		(artwork_id 185963)
		(artwork_name "Cauldron")
		(artwork_in_room [room202])
		(created_by [author367])
		(artwork_in_period [Romanesque])
		(artwork_theme "Antiquity")
		(default_time 4)
	)
	(artwork_869 of Artwork
		(artwork_id 869)
		(artwork_name "The Watermill with the Great Red Roof")
		(artwork_in_room [room202])
		(created_by [author0])
		(artwork_in_period [High_Baroque])
		(artwork_theme "Love")
		(default_time 6)
	)
	(artwork_16298 of Artwork
		(artwork_id 16298)
		(artwork_name "Portrait of Jean Gros (recto); Coat of Arms of Jean Gros (verso)")
		(artwork_in_room [room202])
		(created_by [author42])
		(artwork_in_period [Early_Renaissance])
		(artwork_theme "Love")
		(default_time 4)
	)
	(artwork_15401 of Artwork
		(artwork_id 15401)
		(artwork_name "At Mouquin's")
		(artwork_in_room [room202])
		(created_by [author36])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Despair")
		(default_time 6)
	)
	(artwork_28849 of Artwork
		(artwork_id 28849)
		(artwork_name "A City Park")
		(artwork_in_room [room101])
		(created_by [author78])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_107300 of Artwork
		(artwork_id 107300)
		(artwork_name "Tall-Case Clock")
		(artwork_in_room [room101])
		(created_by [author255])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 6)
	)
	(artwork_34181 of Artwork
		(artwork_id 34181)
		(artwork_name "La durée poignardée (Time Transfixed)")
		(artwork_in_room [room102])
		(created_by [author83])
		(artwork_in_period [Surrealism])
		(artwork_theme "Magic")
		(default_time 6)
	)
	(artwork_156474 of Artwork
		(artwork_id 156474)
		(artwork_name "Relaxing in the Shade")
		(artwork_in_room [room101])
		(created_by [author334])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 7)
	)
	(artwork_87045 of Artwork
		(artwork_id 87045)
		(artwork_name "Still Life with Geranium")
		(artwork_in_room [room101])
		(created_by [author203])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 6)
	)
	(artwork_69780 of Artwork
		(artwork_id 69780)
		(artwork_name "The Fountain, Villa Torlonia, Frascati, Italy")
		(artwork_in_room [room101])
		(created_by [author158])
		(artwork_in_period [Expressionism])
		(artwork_theme "Mysticism")
		(default_time 5)
	)
	(artwork_76816 of Artwork
		(artwork_id 76816)
		(artwork_name "The Young Emperor Akbar Arrests the Insolent Shah Abu’l-Maali, Page from a Manuscript of the Akbarnama")
		(artwork_in_room [room101])
		(created_by [author181])
		(artwork_in_period [Mannerism])
		(artwork_theme "Mysticism")
		(default_time 3)
	)
	(artwork_16568 of Artwork
		(artwork_id 16568)
		(artwork_name "Water Lilies")
		(artwork_in_room [room201])
		(created_by [author49])
		(artwork_in_period [Expressionism])
		(artwork_theme "Joy")
		(default_time 6)
	)
	(artwork_189290 of Artwork
		(artwork_id 189290)
		(artwork_name "Gingold Living Room End Table (2 of 2)")
		(artwork_in_room [room101])
		(created_by [author379])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_91620 of Artwork
		(artwork_id 91620)
		(artwork_name "Portrait Vessel of a Ruler")
		(artwork_in_room [room103])
		(created_by [author219])
		(artwork_in_period [Rococo])
		(artwork_theme "Fauna")
		(default_time 4)
	)
	(artwork_184095 of Artwork
		(artwork_id 184095)
		(artwork_name "Near the Lagoon")
		(artwork_in_room [room103])
		(created_by [author352])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Occult")
		(default_time 4)
	)
	(artwork_11393 of Artwork
		(artwork_id 11393)
		(artwork_name "Henry Ossawa Tanner")
		(artwork_in_room [room201])
		(created_by [author25])
		(artwork_in_period [Realism])
		(artwork_theme "Battles and Wars")
		(default_time 5)
	)
	(artwork_18709 of Artwork
		(artwork_id 18709)
		(artwork_name "The Frugal Meal, from The Saltimbanques")
		(artwork_in_room [room201])
		(created_by [author53])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Nostalgia")
		(default_time 4)
	)
	(artwork_63554 of Artwork
		(artwork_id 63554)
		(artwork_name "Big River, from the Rancherie, Mendocino, California")
		(artwork_in_room [room201])
		(created_by [author142])
		(artwork_in_period [Realism])
		(artwork_theme "Battles and Wars")
		(default_time 6)
	)
	(artwork_199002 of Artwork
		(artwork_id 199002)
		(artwork_name "In Memory of My Father")
		(artwork_in_room [room203])
		(created_by [author397])
		(artwork_in_period [Pop_Art])
		(artwork_theme "Joy")
		(default_time 6)
	)
	(artwork_105073 of Artwork
		(artwork_id 105073)
		(artwork_name "The Creation of Adam")
		(artwork_in_room [room102])
		(created_by [author248])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Occult")
		(default_time 3)
	)
	(artwork_218612 of Artwork
		(artwork_id 218612)
		(artwork_name "Khee II")
		(artwork_in_room [room203])
		(created_by [author403])
		(artwork_in_period [Pop_Art])
		(artwork_theme "Joy")
		(default_time 8)
	)
	(artwork_220179 of Artwork
		(artwork_id 220179)
		(artwork_name "Object with Number 1")
		(artwork_in_room [room103])
		(created_by [author404])
		(artwork_in_period [Expressionism])
		(artwork_theme "Astrology")
		(default_time 4)
	)
	(artwork_79507 of Artwork
		(artwork_id 79507)
		(artwork_name "Pillars of the Country")
		(artwork_in_room [room103])
		(created_by [author185])
		(artwork_in_period [Proto-Renaissance])
		(artwork_theme "Astrology")
		(default_time 7)
	)
	(artwork_46230 of Artwork
		(artwork_id 46230)
		(artwork_name "Reliquary Casket of Saints Adrian and Natalia")
		(artwork_in_room [room202])
		(created_by [author101])
		(artwork_in_period [Romanesque])
		(artwork_theme "Antiquity")
		(default_time 3)
	)
	(artwork_50276 of Artwork
		(artwork_id 50276)
		(artwork_name "Statue of the Madonna in the Mountains")
		(artwork_in_room [room202])
		(created_by [author111])
		(artwork_in_period [Romanticism])
		(artwork_theme "Love")
		(default_time 6)
	)
	(artwork_64339 of Artwork
		(artwork_id 64339)
		(artwork_name "Coffin and Mummy of Pa-ankh-en-Amun")
		(artwork_in_room [room201])
		(created_by [author144])
		(artwork_in_period [Romanticism])
		(artwork_theme "Nostalgia")
		(default_time 6)
	)
	(artwork_73413 of Artwork
		(artwork_id 73413)
		(artwork_name "Bust of a Youth (Saint John the Baptist?)")
		(artwork_in_room [room203])
		(created_by [author170])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Christianity")
		(default_time 4)
	)
	(artwork_80062 of Artwork
		(artwork_id 80062)
		(artwork_name "Edtaonisl (Ecclesiastic)")
		(artwork_in_room [room203])
		(created_by [author187])
		(artwork_in_period [Cubism])
		(artwork_theme "Greek Mythology")
		(default_time 10)
	)
	(artwork_149776 of Artwork
		(artwork_id 149776)
		(artwork_name "The Freedman")
		(artwork_in_room [room101])
		(created_by [author319])
		(artwork_in_period [Impressionism])
		(artwork_theme "Mysticism")
		(default_time 4)
	)
	(artwork_2816 of Artwork
		(artwork_id 2816)
		(artwork_name "Interior at Nice")
		(artwork_in_room [room201])
		(created_by [author2])
		(artwork_in_period [Expressionism])
		(artwork_theme "Sadness")
		(default_time 6)
	)
	(artwork_70207 of Artwork
		(artwork_id 70207)
		(artwork_name "Kneeling Figure")
		(artwork_in_room [room203])
		(created_by [author161])
		(artwork_in_period [Realism])
		(artwork_theme "Battles and Wars")
		(default_time 5)
	)
	(artwork_65868 of Artwork
		(artwork_id 65868)
		(artwork_name "Silver Sun")
		(artwork_in_room [room102])
		(created_by [author150])
		(artwork_in_period [Surrealism])
		(artwork_theme "Magic")
		(default_time 5)
	)
	(artwork_27307 of Artwork
		(artwork_id 27307)
		(artwork_name "Madame de Pastoret and Her Son")
		(artwork_in_room [room201])
		(created_by [author71])
		(artwork_in_period [Romanticism])
		(artwork_theme "Sadness")
		(default_time 6)
	)
	(artwork_14591 of Artwork
		(artwork_id 14591)
		(artwork_name "Woman Reading")
		(artwork_in_room [room201])
		(created_by [author32])
		(artwork_in_period [Realism])
		(artwork_theme "Sadness")
		(default_time 5)
	)
	(artwork_50157 of Artwork
		(artwork_id 50157)
		(artwork_name "Mondrian's Glasses and Pipe")
		(artwork_in_room [room102])
		(created_by [author110])
		(artwork_in_period [Surrealism])
		(artwork_theme "Magic")
		(default_time 3)
	)
	(artwork_189600 of Artwork
		(artwork_id 189600)
		(artwork_name "Fragment")
		(artwork_in_room [room202])
		(created_by [author381])
		(artwork_in_period [Gothic])
		(artwork_theme "Antiquity")
		(default_time 4)
	)
	(artwork_52679 of Artwork
		(artwork_id 52679)
		(artwork_name "The Pheasants from the Verdures of the Vatican Series")
		(artwork_in_room [room101])
		(created_by [author116])
		(artwork_in_period [Romanticism])
		(artwork_theme "Mysticism")
		(default_time 6)
	)
	(artwork_14598 of Artwork
		(artwork_id 14598)
		(artwork_name "The Beach at Sainte-Adresse")
		(artwork_in_room [room102])
		(created_by [author33])
		(artwork_in_period [Realism])
		(artwork_theme "Landscapes")
		(default_time 6)
	)
	(artwork_83905 of Artwork
		(artwork_id 83905)
		(artwork_name "That Which I Should Have Done I Did Not Do (The Door)")
		(artwork_in_room [room102])
		(created_by [author196])
		(artwork_in_period [Surrealism])
		(artwork_theme "Magic")
		(default_time 7)
	)
	(artwork_34116 of Artwork
		(artwork_id 34116)
		(artwork_name "Cabinet")
		(artwork_in_room [room203])
		(created_by [author82])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Christianity")
		(default_time 7)
	)
	(artwork_35376 of Artwork
		(artwork_id 35376)
		(artwork_name "Equestrienne")
		(artwork_in_room [room201])
		(created_by [author87])
		(artwork_in_period [Romanticism])
		(artwork_theme "Nostalgia")
		(default_time 4)
	)
	(artwork_61128 of Artwork
		(artwork_id 61128)
		(artwork_name "At the Moulin Rouge")
		(artwork_in_room [room101])
		(created_by [author134])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Mysticism")
		(default_time 7)
	)
	(artwork_103887 of Artwork
		(artwork_id 103887)
		(artwork_name "A Young Lady with a Parrot")
		(artwork_in_room [room103])
		(created_by [author243])
		(artwork_in_period [Rococo])
		(artwork_theme "Greek Mythology")
		(default_time 5)
	)
	(artwork_21023 of Artwork
		(artwork_id 21023)
		(artwork_name "Buddha Shakyamuni Seated in Meditation (Dhyanamudra)")
		(artwork_in_room [room202])
		(created_by [author59])
		(artwork_in_period [Gothic])
		(artwork_theme "Antiquity")
		(default_time 7)
	)
	(artwork_15563 of Artwork
		(artwork_id 15563)
		(artwork_name "The Night is Stirring (La nuit remue)")
		(artwork_in_room [room202])
		(created_by [author38])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Despair")
		(default_time 7)
	)
	(artwork_4884 of Artwork
		(artwork_id 4884)
		(artwork_name "Figure with Meat")
		(artwork_in_room [room101])
		(created_by [author10])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Mysticism")
		(default_time 7)
	)
	(artwork_4081 of Artwork
		(artwork_id 4081)
		(artwork_name "Gian Lodovico Madruzzo")
		(artwork_in_room [room103])
		(created_by [author3])
		(artwork_in_period [Mannerism])
		(artwork_theme "Christianity")
		(default_time 7)
	)
	(artwork_16487 of Artwork
		(artwork_id 16487)
		(artwork_name "The Bay of Marseille, Seen from L'Estaque")
		(artwork_in_room [room202])
		(created_by [author45])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Despair")
		(default_time 6)
	)
	(artwork_234781 of Artwork
		(artwork_id 234781)
		(artwork_name "Christ Carrying the Cross")
		(artwork_in_room [room103])
		(created_by [author419])
		(artwork_in_period [High_Renaissance])
		(artwork_theme "Nostalgia")
		(default_time 6)
	)
	(artwork_80479 of Artwork
		(artwork_id 80479)
		(artwork_name "Winter, from The Seasons")
		(artwork_in_room [room203])
		(created_by [author189])
		(artwork_in_period [High_Baroque])
		(artwork_theme "Christianity")
		(default_time 11)
	)
	(artwork_105466 of Artwork
		(artwork_id 105466)
		(artwork_name "The Battle between the Gods and the Giants")
		(artwork_in_room [room202])
		(created_by [author251])
		(artwork_in_period [Early_Baroque])
		(artwork_theme "Monarchies")
		(default_time 3)
	)
	(artwork_66683 of Artwork
		(artwork_id 66683)
		(artwork_name "Rodin, Le Penseur")
		(artwork_in_room [room102])
		(created_by [author154])
		(artwork_in_period [Post-Impressionism])
		(artwork_theme "Occult")
		(default_time 4)
	)
	(artwork_111810 of Artwork
		(artwork_id 111810)
		(artwork_name "Harvest Talk")
		(artwork_in_room [room202])
		(created_by [author282])
		(artwork_in_period [Abstract_Expressionism])
		(artwork_theme "Despair")
		(default_time 5)
	)
	(artwork_36132 of Artwork
		(artwork_id 36132)
		(artwork_name "Cope")
		(artwork_in_room [room103])
		(created_by [author88])
		(artwork_in_period [Early_Renaissance])
		(artwork_theme "Christianity")
		(default_time 8)
	)
)
